Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Models/ActorDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DemoExistingDbMVC.Models
{
    public partial class ActorDbContext : DbContext
    {
        public ActorDbContext()
        {
        }

        public ActorDbContext(DbContextOptions<ActorDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Actors> Actors { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.6-servicing-10079");
        }
    }
}

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Models/Actors.cs
using System;
using System.Collections.Generic;

namespace DemoExistingDbMVC.Models
{
    public partial class Actors
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public bool AcademyWinner { get; set; }
    }
}

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Models/ErrorViewModel.cs
using System;

namespace DemoExistingDbMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Controllers/ActorsController.cs
using DemoExistingDbMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoExistingDbMVC.Controllers
{
    public class ActorsController: Controller
    {
        
        private ActorDbContext _context;
        private ILogger<ActorsController> _logger;
        public ActorsController(ActorDbContext context, ILogger<ActorsController>logger)
        {
            _context = context;
            _logger = logger;
        }
        public IActionResult Index()
        {
            try
            {
                var data = _context.Actors.ToList();
                _logger.LogInformation("***Success hitting the index page");
                return View(data);
            }
            catch (Exception ex)
            {
                _logger.LogInformation($"Failed to get records in the Index page:{ex.Message}");
                throw;
            }

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Actors actors)
        {
            if (ModelState.IsValid)
            {
                _context.Actors.Add(actors);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(actors);
        }
    }
}

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoExistingDbMVC.Models;

namespace DemoExistingDbMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Views/Actors/Create.cshtml
@model Actors

@{
    ViewBag.Title = "New Actor";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Actors" asp-action="Create" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>

        <!-- Name -->
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <!-- Age -->
        <label asp-for="Age" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Age" class="form-control" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
        <!-- AcademyWinner -->
        <label asp-for="AcademyWinner" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="AcademyWinner" class="form-control" />
            <span asp-validation-for="AcademyWinner" class="text-danger"></span>
        </div>
        <!-- Create -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Views/Actors/Index.cshtml
@model IEnumerable<DemoExistingDbMVC.Models.Actors>
@{
    ViewBag.Title = "New Actor";
}

<h2>Actors</h2>
<p>
    <a asp-controller="Actors" asp-action="Create">Create New</a>
</p>


<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Age</th>
        <th>AcademyWinner</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademyWinner)
            </td>
        </tr>
    }

</table>

Learning Entity Framework Core/DemoExistingDbMVC/DemoExistingDbMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>